josephdadams/TallyArbiter

views/tally.html

noSleep.enable() "must be wrapped in a user input event handler e.g. a mouse or touch handler" in order to work.
It was not working properly on some older Android 4.1 devices because it was called inside on onLoad().
This will fix it

Call NoSleep from within a user input event handler

---

index.js
package-lock.json
views/static/lib/js/admin.js

From Settings > Devices > Edit Sources there is now the option to select the source from a drop down list populated from the source. The option to enter manually is retained. This will currently only work for OBS and in theory for Tricaster, the storage objects used for ATEM and Analog Way appear to be different abstraction objects, perhaps worth harmonising in the future?
OBS Source tally list is updated automatically when the OBS instance adds, renames or deletes. Renames are rippled through, deletes are not.

Added GUI selection of OBS addresses/sources and automatic updates of the data which holds these

---

index.js

If the M5Stick was once connected to the server and one would change the name of a device, it does not get updated on the M5Stick because the deviceID is still valid.
Secondly, if there is a valid device ID the device_states are not getting send during connection and only on the next switch.
Both issues where fixed by moving the sending the information outside of the if statement.
Note: The devices message must be send before changing the deviceId to set the correct DeviceName that gets displayed on the M5Stick.

Always send devices list when a M5Stick registers as a listener.

---

index.js
package-lock.json

I modified the outgoing web hook mechanism to extend it so that it can be used for sending json requests.
I personally use this to setup actions to control tp-link smart plugs through the outgoing web hook actions.
I added the protocol because the service communicates over https.
I also added content to set the content type of the request. JSON Will set the content-type to JSON. RAW will not set the content-type.

Allow HTTPS JSON Requests for Outgoing Webhooks

---

index.js

Update to use the correct path from Atem Mini to "video.mixEffects" not "video.ME" on line 2539

Update tally from Atem

---

index.js
package.json

Hi, added support for Panasonic AV-HS410 mixers. 
I also added some yarn scripts for simpler dev work and deamon setup.
and a parameter for choosing what port to launch the vMix emulator on, just for those cases where Tally Arbiter is used on a system with vMix running.

Added Support for AV-HS410 Video Mixers

---

dev-app-update.yml
main.js
package-lock.json
package.json

Implements the auto-update functionality for Electron.
When an update is detected, the user is prompted whether he wants to install the update or not. The update is downloaded in the background and once finished, the user is prompted again to save his work and press the Update button. The second dialog is not attached to the main window to not prevent interaction like saving or closing modals.
_Originally requested by @MatteoGheza in https://github.com/josephdadams/TallyArbiter/issues/87#issuecomment-876480735_

Auto-Updater for Electron

---

.dockerignore
.github/workflows/build.yml
.gitpod.yml
Dockerfile
Dockerfile.standalone
docs/docs/developers/tally-arbiter.md
docs/docs/installation/cli.md
docs/docs/installation/docker.md
docs/docs/installation/from-source.md
docs/docs/usage/sections/listener-clients.md
docs/docs/usage/sections/sources.md
docs/docs/usage/sections/tsl.md

@hrueger https://github.com/josephdadams/TallyArbiter/pull/87#issuecomment-846372039 if you want to try this, I suggest you to go to https://gitpod.io/#https://github.com/josephdadams/TallyArbiter/pull/103 and login with Github

Initial Docker and Gitpod support

---

index.js
package-lock.json
package.json

The logs are written to a logs folder under the TallyArbiter folder and the tally_data is written to a TallyData folder in the same place 
The logs use the .talog extension and tally data uses the .tadata extension. 
I am using the find-remove package to find and remove log and tally data files older than 1 week.

Writes logs and tally data to their own file and deletes any log or tally data file older than 1 week

---

UI/src/app/_components/settings/settings.component.ts

When you try to create an OSC source type, it will throw an error because it think that the information field needs to be filled.

Osc sourcetype patch

---

UI/src/app/_components/login/login.component.html
UI/src/app/_components/login/login.component.ts
UI/src/app/_services/auth.service.ts
index.js
package-lock.json
package.json

Currently, logins are vulnerable to brute force, since there are no rate limits to the login event in websocket.
I tried implementing rate limits using an advaced library, [rate-limiter-flexible](https://github.com/animir/node-rate-limiter-flexible), so, in the future, we can implement rate limits to the entire application using a custom Express middleware (for example [https://github.com/animir/node-rate-limiter-flexible/wiki/Express-Middleware](https://github.com/animir/node-rate-limiter-flexible/wiki/Express-Middleware)) and/or Websocket connections (https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#websocket-single-connection-prevent-flooding).
P.S: I added "-1" in `login_response` to maintain compatibility with "old `login_response` versions"

Support for rate limiter and brute force protection

---

UI/src/app/_components/settings/settings.component.html
UI/src/app/_models/DeviceSource.ts
index.js

This will allow the user to rename their TA Devices based on the incoming mnemonic/label of the source's tally data (for tsl, obs, et al). The user can select per device-source mapping if they want it to rename their Device or not.

device renaming

---

index.js
package-lock.json
package.json

As described in #195 
Everything is compatible with the old version of the logger, except that now every line of server logs is similar to
```[2021-08-31 21:53:19] info: Starting HTTP Server.``` or ```[2021-08-31 21:53:40] error: An error occurred etc```
-------------
_Winston options for file output:_
Current options used in server loggin and in Tally data:
```javascript
{
filename: filepath,
maxsize: 3e+7
maxFiles: 3,
...
}
```
-------------
@JTF4 can you explain to me what is Tally data logging and why its format is
`{TallyObj},  {TallyObj}, {TallyObj},`?

Migrate logging and tally data to Winston

---

package-lock.json
package.json
src/actions/OSC.ts

- Fixes an issue where the `isNaN` function was not working by replacing it with `Number.isNaN`
- Fixes an issue where the function that processes the arguments gets stuck in an infinite loop

Fix OSC issues

---

listener_clients/relay-listener/index.js

When the save config function was called when `useMDNS` was fase, it would reset the `useMDNS` value to true because of the `!server_config.useMDNS` call.

Fixed an issue with save config function

---

src/_helpers/configSchema.ts
src/_models/DeviceSource.ts
src/_models/Source.ts
src/index.ts
src/sources/_Source.ts

The reconnect handling for device sources has been extended with the options:
- reconnect_intervall (number)
- unlimited_reconnects (boolean)
**Reconnect_intervall** is only used if larger than the constant RECONNECT_INTERVAL. 
**Unlimited_reconnects** is only used if set to true. If false or not set the default MAX_FAILED_RECONNECTS is used.
NB: Additional console printouts for easier troubleshooting was included.

Configurable reconnect handling

---

listener_clients/TTGO_T-listener/README.md

Adjusted the repo link to a folder within Tally Arbiter. It could be argued that this should not be changed since it is a historic reference regarding the initial code base.

Updated repo link

---

.github/workflows/build-listener-clients.yaml
.github/workflows/build.yml

This is to make sure that new PRs don't break the CI once they are merged (at least we'll see that jobs fail before merging).
That is probably a good idea also to ensure that workflows don't intruduce build problems.
Created because of #333 which looked ok with the workflows that did run, but once merged it broke ;-)

run workflows on `pull_request` event

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

Static IP functionality for the M5 Atom was partly removed (commented) from PR #333, but the subsequent use of the static IP variables remained, preventing the listener from compiling for the last month. This PR comments out those references as well.
I am not well versed in C++ or Git (at all), so feel free to point out better ways to fix this issue.

Remove references to undeclared static IP variables from M5Atom listener

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

The code wasn't converting the RGB to GRB.
It maintained the RGB in original code and displayed the colors Green and Red swapped.
With this correction the colors are now in GRB form and displayed correctly.

RGB to GRB bug correction

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

actualType is literally the type between "" (ex: "program") so an escape sequence is needed  for the arduino interpreter to acknowledge the quotes when comparing

Fixed Tally Extra Output not working

---

listener_clients/relay-listener/index.js

While trying to get relays configured properly and working on a fresh system I came across a state where ProcessTallyData was calling getRelayGroupById with a deviceId that didn't match any of the relay groups. The for loop in getRelayGroupById went through 5 of my 4 relay groups which resulted in comparing the deviceId property on an undefined item from the array and errored out.
After fixing the off by one, the getRelayGroupById function was returning undefined due to the deviceId not matching any groups and ProcessTallyData errored out when trying to compare property deviceId on undefined.

Fix off by one error and unhandled undefined in relay-listener

---

.github/workflows/build-listener-clients.yaml

Arduino compilation tests failing because WiFi.h can't find a file included with the Arduino ESP32 core library. I am going to try adding the Arduino ESP32 core library to the workflow and see if it helps.

Fix ESP32 Listener Client Build Errors

---

UI/src/app/_components/about/about.component.html
listener_clients/M5AtomMatrix-listener/README.md
listener_clients/TTGO_T-listener/README.md
listener_clients/blink1-listener/README.md
listener_clients/esp32-neopixel-listener/README.md
listener_clients/gpo-listener/README.md
listener_clients/m5stickc-listener/README.md
listener_clients/relay-listener/README.md
readme.md

Closes #363
I tried to replace every reference to the blog in contact information and in the "about" section of the UI, as suggested by @JTF4.

Update techministry.blog references

---

UI/src/app/_components/chat/chat.component.ts
UI/src/app/_components/tally/tally.component.html
UI/src/app/_components/tally/tally.component.ts

Tally View - Add Checkbox for Enable Chat/Disable Chat and automatically add ?chat=false as query params to url
Chat components can use device name instead of client only, so producer and other client can differentiate the chat is come from who.

Some UI Change on Tally View pages and chat components

---

UI/src/app/_components/settings/settings.component.html
package-lock.json
package.json
src/_decorators/RegisterNetworkDiscovery.decorator.ts
src/sources/BlackmagicATEM.ts

Improve Atem source

---

UI/angular.json
UI/src/app/_services/conn-lost-snackbar.service.ts
UI/src/app/_services/socket.service.ts
UI/src/app/app.component.html
UI/src/app/app.component.scss
UI/src/app/app.component.ts
UI/src/app/app.module.ts

Fixed an old error introduced by me with server reconnection. Now it works.
I tried to add a "snackbar" to notify the user if the client losts connection, but I'm not a designer and I'm a noob at CSS. Let me know what do you thing.

Fix server reconnection, add conn. lost snackbar

---

package.json

Updated typescript from 4.6.4 to5.1.6 in devDependencies in package.json to solve failure in automatic build checks.

Change typescript 4.6.4 to 5.1.6 in package.json

---

listener_clients/gpo-listener/gpo-listener.py
src/index.ts

Corrected a few errors preventing the GPO listener client connecting to the server and handling device reassignment properly. Made similar changes to `src/index.ts` for relay listener, too (untested).

GPO listener client connection and device reassignment

---

listener_clients/m5stickc-listener/README.md
listener_clients/m5stickc-listener/m5stickc-listener.ino

When trying to use a M5StickC, I found that I was unable to setup the tallyarbiter ip address in the UI. 
In the Serial Monitor it wrote `WiFiManagerParameter is out of scope` which took me to https://github.com/tzapu/WiFiManager/issues/1615.
The change in this PR fixed it for me.
I have also added to the documentation for this listener some additional notes about reconfiguring a device, to clarify it is possible to reconfigure without needing to reflash the device.

fix(m5stick): tally-arbiter fields not showing in setup interface

---

.github/workflows/build-listener-clients.yaml

Upgraded:
* Dependencies to M5 libraries to the latest versions
* Latest GitHub actions in order to use node version 20. Removes the deprecation warnings when running the actions.

Upgrade dependency for Listener GitHub Actions

---

.github/workflows/build-listener-clients.yaml

In the latest version (currently v2.5.34) of TTF_eSPI was a direct reference added to hal/gpio_11.h. This breaks the build of the TTGO listeners in TallyArbiter, a temporary workaround is to for the build to use v2.5.33.

Fix build errors in Build Listener Clients for TTGO listeners

---

docs/docs/usage/sections/sources.md
readme.md

Updated minimum Node.js from 14.17 to 18.13, this is due to Angular CLI dependency.
Updated OBS Studio with clarification that obs-websocket is for pre v28.

Doc updates

---

src/sources/NewtekTricaster.ts

The bus clearing is now only done for preview or program based on the received Tricaster input. So one at a time can be updated/cleared.
The testing when pushing the Tricaster fix was not done with a single preview or program status update, now it works. This is a fix for https://github.com/josephdadams/TallyArbiter/issues/623.

Only clear Tricaster program or preview when new tally data is received

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml

Updates in workspaces for **Build** and **CodeQL code scanning**.
**Build CLI on Ubuntu**
JS-DevTools/npm-publish@v1 changed to JS-DevTools/npm-publish@v3
to solve:
The following actions uses node12 which is deprecated and will be forced to run on node16: JS-DevTools/npm-publish@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
**Build Docker image on Ubuntu**
crazy-max/ghaction-docker-meta@v2 changed to crazy-max/ghaction-docker-meta@v3
docker/login-action@v1 changed to docker/login-action@v3
docker/build-push-action@v2 changed to docker/build-push-action@v5
docker/build-push-action@v2 changed to docker/build-push-action@v5
to solve:
> The following actions uses node12 which is deprecated and will be …

 Updates in workspace to solve errors and warnings

---

.gitpod.yml
Dockerfile
package-lock.json
package.json
src/_helpers/auth.ts

This change was done in:
`src/_helpers/auth.ts`
`package.json`
Replace was also made in
`Dockerfile`
but I'm not certain that we need it here. Can it be removed in this part? This can perhaps be sorted out later.
It was removed in
`.gitpod.yml`
since we should not need to rebuild this package.
The purpose is to fix https://github.com/josephdadams/TallyArbiter/issues/603.
bcrypt.js: https://github.com/dcodeIO/bcrypt.js#readme
bcrypt: https://github.com/kelektiv/node.bcrypt.js#readme

Replacing bcrypt with bcryptjs

---

UI/package-lock.json
UI/package.json
package-lock.json

This PR clean up the dependencies
```
npm WARN deprecated dgram@1.0.1: npm is holding this package for security reasons. As it's a core Node module, we will not transfer it over to other users. You may safely remove the package from your dependencies.
npm WARN deprecated @types/socket.io-client@3.0.0: This is a stub types definition. socket.io-client provides its own type definitions, so you do not need this installed.
```
These things were reported in https://github.com/josephdadams/TallyArbiter/issues/579.
There are a number of npm audit things to fix in the UI part connected to _axio_ and _vite_ but that requires more testing then I today have time for. Note that there is today no solution for the issue with _sweetalert2_.
**axios**
Specific dependency to 0.21.4 in …

Fix 579 dependencies dgram@1.0.1 and @types/socket.io-client@3.0.0

---

listener_clients/M5AtomMatrix-listener/README.md
listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino
listener_clients/m5stickc-listener/README.md
listener_clients/m5stickc-listener/m5stickc-listener.ino

**m5stickc**
Adjusted screen brigthness on m5stickcplus.
Updated showdevice page on m5stickcplus.
Updated m5stickc ReadMe
**m5atom**
Updated WiFI AP to use 3 bytes of mac address on m5atom.
Updated to use 3 bytes of  mac address in device name for m5atom
Added define to build with or without camber number during pvw and pgm for m5atom
Updated m5atom ReadMe

Clean-up in m5atom and m5stick listeners

---

listener_clients/blink1-listener/README.md

The TallyArbitor for blink client will not run unless the zeroconf lib is installed

Adding zeroconf to the list of required libraries for install

---

main.js

Currently, if app is still running and the mac os is shutdown, the app prevents shutdown. This allows the shutdown to close the app.

Allow shutdown on mac while app is running

---

package-lock.json
package.json

Reverting axios (update previously made in https://github.com/josephdadams/TallyArbiter/pull/607).
In order to step to axios 1.6.0 the change in axios from Common JS to ES Module needs to be handled, this it not quickly done. This revert is only to make a release more sucessfull. A new issue will be created to track this technical debt.
When this PR has been merged to main is the suggestion that we go ahead with a new release since there are several queued up fixes that would be good to have in a formal release package.
Fixes https://github.com/josephdadams/TallyArbiter/issues/640

Revert axios (1.6.0 to 0.27.2)

---

docs/docs/usage/sections/devices.md
package-lock.json
package.json
src/actions/Ember.ts

I tested this against a Lawo console running 6.4.0.19 and one running 10.8.0.1.  
The ember path needs to be collected & verified using something like Ember+ viewer (available freely online).
Action uses a static dictionary of connections to reuse existing ember+ connections.  Connecting initially to Ember+ can result in a delay that is not great for AfV operations based on tally.

Add Ember+ support as an outgoing action

---

listener_clients/gpo-listener/gpo-listener.py

This could be a fix for https://github.com/josephdadams/TallyArbiter/issues/661. Based on code inspection is looks plausible but I don't have any board to test with at the moment.

Added in on_flash support for output_invert for lastState.

---

.github/workflows/build-listener-clients.yaml
listener_clients/TTGO_T-listener/TTGO_T-listener.ino

Removed the TFT_eSPI specific dependency to v2.5.33. Now latest version of TFT_eSPI can be used. It was verified with v2.5.43. This is a solution to https://github.com/josephdadams/TallyArbiter/issues/618.
The solution was to change the include order of TFT_eSPI in `TTGO_T-listener.ino` so that latest version of TFT_eSPI can be referenced in the build file.
NB: The failure in `Run arduino/compile-sketches@v1` is due to a memory usage size check with the previous sketch which will fail with this PR. I was lazy and didn't want to split this PR into two PRs where the include line is changed in the first PR and then the build file is changed in the second PR.

Remove TFT_eSPI specific dependency

---

Dockerfile

The freetype2 npm package has prebuilt bindings, but not for all platforms supported by the TallyArbiter docker image. This fixes the issue by rebuilding the freetype2 dependency during the docker image build.
Closes issue #683

Fix freetype dependency in docker build for all platforms

---

listener_clients/m5stickc-listener/README.md
listener_clients/m5stickc-listener/m5stickc-listener.ino

Improvements
- Added support for m5stickC-Plus2.
- Changed pin for tally extra preview. (G36 is input only, it was replaced by G25 but it doesn't exist on the plain m5stickC)
- Changed HIGH/LOW for external leds. (On m5stickC and m5stickC-plus is HIGH and LOW not the same for the internal led as on external leds)
- Replaced code internal defines for board types with board defines used by Arduino IDE.
Things to fix in the future:
- Fix battery level for M5stickC-Plus2.
- Add screen brightness for M5stickC-Plus2.

Added support for m5stickC-Plus2

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

adding variable up the top
Changes:
- Autorotation! Display will now display the numbers in the correct orientation during tally changes - added as some of my cameras I mount using a stiff USB cable into a v-mount battery
- Colours from TallyArbiter now are correct
- Changed GRB_COLOR to RGB_COLOR as someone else changed the values to read RGB instead of GRB
- Swapped R&G Channels in the HEX converter
- Added the following colors "WarmWhite" "DIMWarmWhite"
- Reduced the RGB_COLOR_GREEN as green was significantly brighter than RED or BLUE
- Continued to add more inconsistant comments
- fixed several spelling mistakes
- added several spelling mistakes
To Do:
- Add persistant Show numbers during tally must be set durning wifi setup
- Allow setting to allow persistant access to WifiManager …

Client Updates

---

package-lock.json
src/index.ts

Improved the support for linked busses by updating:
- `function getDeviceStates` - added linked busses logic
- `function UpdateDeviceState` - changed id to sourceId and added linked busses logic
- `function initializeSource` - changed id to sourceId
This PR solves https://github.com/josephdadams/TallyArbiter/issues/704.
As a consequence this PR improves RunAction when defining multiple devices for the same source.
As a consequence the code to check the status for linked busses is now duplicated. This can later be improved.

Improving linked busses support

---

src/actions/OSC.ts

Small correction in OSC RunAction:
- Added regex to identify if not float32 nor int32 then string.
- Corrected variable for oscUDP send so that data is actually sent.
This is a fix for https://github.com/josephdadams/TallyArbiter/issues/707.

Fix OSC argument not sent in RunAction

---

package-lock.json
package.json
src/sources/OBS.ts

Support for nested OBS scenes added in source type OBS for websocket5. The support and behaviour with nested scenes is now the same for both websocket4 and websocket5 in TA.
This is a fix for https://github.com/josephdadams/TallyArbiter/issues/527 including its duplicate https://github.com/josephdadams/TallyArbiter/issues/665.
NB: Support for group is not added.

Added support for nested OBS scenes for websocket5

---

src/sources/SimplyLive.ts
src/sources/TSL.ts

Allow TSL packages without a source name.
In case there is no name provided, dont update the address label.
Note: I will check how i can unify the code in TSL & SimplyLive in the next step, when building the generic TSL options.
Just wanted to separate this change to not mix up things.

TSL packages without name

---

docs/docs/usage/control-interface.md
listener_clients/m5stickc-listener/README.md
listener_clients/m5stickc-listener/m5stickc-listener.ino

Refactoring of defines in the ino file:
- Refactor the support for defines when using Arduino IDE. This should solve https://github.com/josephdadams/TallyArbiter/issues/763.
- Added check for multiple defines.
- Added differention so that it is visible if it is a m5stickc, m5stickc-plus or m5stickc-plus2 both in the logging in the m5stick hardware and in the Tally Arbiter server.
- Refactor code with board types defines for increased readability.
- Updated documentation regarding config.json path on linux when using sudo. This should solve https://github.com/josephdadams/TallyArbiter/issues/775.
- Added information regarding import/export. This should solve https://github.com/josephdadams/TallyArbiter/issues/774.

Refactor building for different m5stickc boards

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

Sometimes, when you press the button on the M5Atom, it doesn't get updated, but the server still recieves it.

Fix the camera number sometimes not getting updated | M5Atom

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

When the M5Atom is flashed, it stops showing the camera number.

Draw camera number after flashing | M5Atom

---

.github/workflows/build-listener-clients.yaml
listener_clients/TTGO_T-listener/TTGO_T-listener.ino
listener_clients/esp32-neopixel-listener/esp32-neopixel-listener.ino

Updated from actions/upload-artifact: v3 to actions/upload-artifact: v4.
Updated fqbn for M5Atom and M5Stickc. Changed - to _.
Uppdated TTGO code to new WiFiEvents.
NB: Testing of the builds have not been done, only updating the builds so that they build sucessfully. The build for TTGO fails due too large image.

Fix listener automatic builds

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

Two error corrections and one performance improvement for m5atom.
- Corrected so that number is displayed after flash. Solved: https://github.com/josephdadams/TallyArbiter/issues/394
- Corrected so that number is not incremented when tally is triggered. Solved: https://github.com/josephdadams/TallyArbiter/issues/410
- Removed unnecessary call to updateDisplayBasedOnOrientation().

Corrected m5atom camera number handling after flash and first received tally data

---

src/index.ts

* fixes TSL to report the same state for all devices
* #765
* #778 
* `UpdateDeviceState` derives `currentDeviceTallyData` from `SourceClients` instead of `currentSourceTallyData`
In `sourceClient.tally.subscribe(...)` near `src/index.ts:1353` tally data is prepared for a source.
For every entry, that matches a device_source the tally data is stored per `sourceId` dropping the address.
If multiple entries match (i.e. for the test source), the last match overwrites any previous matches. 
(which leads to odd behavior as described in #765 and #778)
I do not understand the intention of `currentSourceTallyData` for sources referring to multiple addresses.
I found `SourceClients` is used in `getDeviceStates()` (near `index.ts:1125`) and concluded that `SourceClients` contains the needed …

fixes TSL to report the same state for all devices

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

Boot Display Fix:
The camera number wasn't appearing on initial boot until the button was pressed
Added initialization of rotatedNumber during setup
Now displays camera number immediately after WiFi connection

Fix camera number display on boot

---

listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

The Mac-Adress would be 00:00:00:00:00:00, because the WiFi wasn't initialized.

Fix empty Mac-Adress | M5Atom
