index.js
readme.md
views/settings.html

Adds support for all [Livecore series processors](https://www.analogway.com/emea/products/livecore-image-processors/).
Tally data is automatically sent on a TCP socket by these devices as soon as an input enters program or preview.

Add support for Analog Way Livecore image processors

---

index.js

Rewrite of processing of ATEM changes to use `listVisibleInputs` function implemented in atem-connection library.
Features:
- during transition both sources (preview and program) are red (i.e. on program)
- also handles sources in keyers, downstream keys and super source
Fixes issues #20 and #50
I hope I didn't break anything, but as far as I could see all changes should be local to a single atem source.

ATEM: use tally logic implemented in atem-connection library

---

index.js

Merge program/preview information from multiple MEs before processing
Fixes issue #96

Fix handling of multiple ATEM MEs

---

index.js

Log filenames fix

---

UI/src/app/_components/home/home.component.html
electron-builder.json
main.js

- Ignore files for packing app.asar and add category
- Fix documentation opening in the same window

Electron improvements

---

UI/src/app/_services/socket.service.ts

Filter sourceTypes by enabled

---

index.js

on Ross Acuity...
None: LH = 0, RH = 0
PVW: LH = 2, RH = 0
PGM: LH = 0, RH = 1
PVW+PGM: LH = 3, RH = 3

fix tsl5 processing

---

UI/src/app/_components/settings/settings.component.html
UI/src/app/_models/VmixClient.ts
UI/src/app/_services/socket.service.ts
index.js
package-lock.json

I redesigned the vMix listener client handling system in tally arbiter. 
Since vMix clients cant be flashed or reassigned, I moved them to their own area of TallyArbiter

vMix support redesign

---

docs/docs/usage/sections/devices.md
index.js
package-lock.json
package.json

Adds support for outgoing TSL UMD v5 Tallies.
Attempts to include most of the features of the v5 protocol.

add support for outgoing TSL UMD 5

---

docs/docs/installation/desktop-app.md

fixes #181 
This also removes the `Autoupdater will be available soon`.

add docs about the autoupdater

---

UI/src/app/_services/socket.service.ts
index.js

Fix io.sockets.connected and add custom error in TallyArbiter_Remove_Cloud_Client

---

UI/src/app/_components/error-reports-list/error-reports-list.component.html
UI/src/app/_components/error-reports-list/error-reports-list.component.scss
UI/src/app/_components/error-reports-list/error-reports-list.component.ts
index.js
package-lock.json
package.json

Add "(unread)" near unreaded error reports and add "Mark all as read" and "Delete error reports from disk"

---

CODE_OF_CONDUCT.md

Added CODE_OF_CONDUCT.md file to the repo
@MatteoGheza 
@josephdadams 
@hrueger 
@JTF4 
Please review the changes !!

added CODE_OF_CONDUCT.md file 

---

.github/workflows/welcome-first-time-contributor.yml

Pertains to  #258 
Added a github action to welcome first time contributors to the repository
@MatteoGheza
@josephdadams
@hrueger
@JTF4
Please review the changes !!

Added the github action 

---

package.json

Fix npm package.json

---

UI/src/app/_components/settings/settings.component.html
UI/src/app/_components/settings/settings.component.ts
UI/src/app/_services/socket.service.ts
src/_decorators/RegisterNetworkDiscovery.decorator.ts
src/_globals/RegisteredNetworkDiscoveryServices.ts
src/_models/NetworkDiscovery.ts
src/index.ts
src/sources/BlackmagicATEM.ts
src/sources/PanasonicAVHS410.ts

I selected the wrong base when creating the PR.
TODOs:

Discover devices over the network

---

.github/workflows/welcome-first-time-contributor.yml

Removed some of the insane amount of emojies and cleaned up some of the verbiage.

Update welcome mssage

---

listener_clients/blink1-listener/README.md

Adjusted the repo link to a folder within Tally Arbiter.

Updated repo link

---

listener_clients/M5AtomMatrix-listener/README.md
listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/tallyarbiter-m5atom.ino

M5Stick Atom - Reset WiFi credentials when button pressed by 5 seconds

M5Stick Atom - Reset WiFi credentials when button pressed by 5 seconds

---

src/index.ts

This PR seeks to fix a bug I found with the Custom listenerClient API. Addresses issue #305

BUGFIX: Custom listenerClient API

---

UI/src/app/_services/socket.service.ts
src/_helpers/config.ts
src/index.ts

Needs testing. It should fix every JWT-related issue.
Closes #401 #359

Fix JWT auth

---

main.js

This change fixes the issue with the program not being it's min height and min width upon launch.

Update main.js to fix the issue with the application not opening to it min height and width

---

src/_modules/TSL.ts
src/_modules/VMix.ts
src/_modules/_ListenerProvider.ts
src/index.ts

I don't have a vMix setup here to test this, but I found that we're not even starting the vMix Server ;-)
Could someone test this?

Fix #420: vMix Emulator is not started

---

.github/workflows/build-listener-clients.yaml

Reverts josephdadams/TallyArbiter#486 because it made no difference in the build errors in the clients

Revert "Update build-listener-clients.yaml"

---

Dockerfile
Dockerfile.standalone
electron-builder.json

Fix Docker Node Bcrypt error

---

src/sources/VMix.ts

Added connect/reconnect to enable vMix reconnect handling. This is a fix for Issue #532.

vMix reconnect handling

---

src/sources/_Source.ts

Reset reconnectFailureCounter when no more reconnects are triggered. This is a reset step I missed to include in the original feat_reconncts branch.

Reset reconnectFailureCounter after final connection attempt

---

src/sources/AnalogWayLivecore.ts
src/sources/BlackmagicVideoHub.ts
src/sources/NewtekTricaster.ts
src/sources/OBS.ts
src/sources/RolandVR.ts
src/sources/VMix.ts

**Feature**
Added connect/reconnect handling to:
- Roland VR
- Newtek Tricaster
- Analog Way Livecore
**Bugs**
- Improved connect handling in VMix to avoid memory leak since an additional listener was registered at every connect.
- Removed bug in OBS that caused infinite reconnect attempts.
- Removed premature connected status in Blackmagic VideoHub.

Added connect/reconnect to three sources and bug fixes in three sources

---

src/sources/PanasonicAVHS410.ts

Added connect() and reconnect() to align with code structure for 3.x. The refactoring in 3.x created a dependency to reconnect().

Added reconnect

---

src/sources/NewtekTricaster.ts

The refactoring of code between 2.x and 3.x broke the support for NewTek Tricaster. Receive tally data was not properly handled.
I don't have access to an Tricaster but have tested this with SocketTest v3.0.0 by sending input that should be the same as from a real Tricaster.
The example input is:
```
<shortcut_states>
<shortcut_state name="program_tally" value="INPUT1|BFR2|DDR3" type="" sender="" />
<shortcut_state name="preview_tally" value="INPUT7" type="" sender="" />
</shortcut_states>
```
from page 62 in https://downloads.newtek.com/LiveProductionSystems/VMC1/Automation%20and%20Integration%20Guide.pdf
This should fix https://github.com/josephdadams/TallyArbiter/issues/541.

Update NewtekTricaster to handle tally data after refactoring in 3.x

---

listener_clients/blink1-listener/blink1-listener.py

Adding optional flag to disable the blinking on connect, error, disconnect and reconnect

Optionally disable status light blinks

---

docs/docs/usage/control-interface.md
docs/docs/usage/sections/devices.md
docs/docs/usage/sections/sources.md
package-lock.json
src/actions/TSL.ts
yarn.lock

Removed (Preview) and (Program) for Actions TSL 3.1 UDP/TCP.
Rephrased docs.

Fix action tsl UI and doc clean up
